_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 100
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 100
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.11
            "6": 4.38.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
